name: Deploy to SiteGround (STAGING)

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH key
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          printf '%s' "${{ secrets.SG_CI_KEY }}" > ~/.ssh/sg_ci
          sed -i 's/\r$//' ~/.ssh/sg_ci
          chmod 600 ~/.ssh/sg_ci

      - name: Package project
        shell: bash
        run: |
          set -euo pipefail
          TAR="$RUNNER_TEMP/site.tar.gz"
          [ -f .deployignore ] && sed -i 's/\r$//' .deployignore || true
          if [ -f .deployignore ]; then
            tar --exclude-from=.deployignore --exclude=./site.tar.gz -czf "$TAR" .
          else
            tar --exclude=./site.tar.gz -czf "$TAR" .
          fi
          mv "$TAR" ./site.tar.gz
          ls -lh ./site.tar.gz

      - name: Upload & Deploy (STAGING)
        shell: bash
        env:
          SG_HOST: ${{ secrets.SG_HOST }}
          SG_PORT: ${{ secrets.SG_PORT }}
          SG_USER: ${{ secrets.SG_USER }}
        run: |
          set -euo pipefail
          # Upload to HOME (always exists)
          scp -P "$SG_PORT" -i ~/.ssh/sg_ci -o StrictHostKeyChecking=no site.tar.gz "$SG_USER@$SG_HOST:~/"

          # Remote deploy via heredoc (keep closing BASH indented)
          ssh -p "$SG_PORT" -i ~/.ssh/sg_ci -o StrictHostKeyChecking=no "$SG_USER@$SG_HOST" 'bash -s' <<'BASH'
          set -euo pipefail
          DOC="$HOME/public_html/staging"
          mkdir -p "$DOC"
          mv -f "$HOME/site.tar.gz" "$DOC/"
          cd "$DOC"

          # Extract into a temp dir
          rm -rf __new
          mkdir __new
          tar -xzf site.tar.gz -C __new

          # Replace contents without rsync (avoid delete races)
          shopt -s dotglob
          find . -mindepth 1 -maxdepth 1 ! -name '__new' -exec rm -rf {} +
          cp -a __new/
