name: Deploy to SiteGround (SFTP) — Staging & Prod

on:
  push:
    branches: [main, staging]
  workflow_dispatch:
    inputs:
      target:
        description: "Where to deploy"
        required: true
        default: "staging"
        type: choice
        options: [staging, production]

defaults:
  run:
    shell: bash

# Keep staging/prod runs from colliding
concurrency:
  group: deploy-${{ github.event.inputs.target || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SG_PORT: ${{ secrets.SG_PORT }}   # 18765

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select environment (staging/prod)
        id: select
        run: |
          set -euo pipefail
          # Determine TARGET from manual input or branch
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TARGET="${{ github.event.inputs.target }}"
          else
            case "${{ github.ref }}" in
              refs/heads/main)    TARGET=production ;;
              refs/heads/staging) TARGET=staging ;;
              *) echo "::error::Unsupported branch ${GITHUB_REF}"; exit 1 ;;
            esac
          fi

          # Assign DEST_PATH/BASE_URL LOCALLY first (so we can echo them),
          # then export to GITHUB_ENV for later steps.
          if [ "$TARGET" = "production" ]; then
            DEST_PATH='${{ secrets.SG_DEST_PROD }}'
            BASE_URL='https://claycraze.com'
          else
            DEST_PATH='${{ secrets.SG_DEST_STAGING }}'
            BASE_URL='https://staging.claycraze.com'
          fi

          echo "TARGET=$TARGET"           >> "$GITHUB_ENV"
          echo "DEST_PATH=$DEST_PATH"     >> "$GITHUB_ENV"
          echo "BASE_URL=$BASE_URL"       >> "$GITHUB_ENV"

          echo "Deploy target: $TARGET → $DEST_PATH"

      - name: Setup SSH key
        env:
          PRIV: ${{ secrets.SG_PRIVATE_KEY }}
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          printf '%s' "$PRIV" | tr -d '\r' > ~/.ssh/sg-ci
          chmod 600 ~/.ssh/sg-ci

      - name: Show CI key fingerprint
        run: |
          echo "CI key fingerprint (must match SG authorized key):"
          ssh-keygen -y -f ~/.ssh/sg-ci | ssh-keygen -lf -

      # Guardrail: accept SG_EXPECTED_FPR as Variable OR Secret
      - name: Assert CI key fingerprint matches expected
        env:
          EXPECTED_V: ${{ vars.SG_EXPECTED_FPR }}
          EXPECTED_S: ${{ secrets.SG_EXPECTED_FPR }}
        run: |
          set -euo pipefail
          EXPECTED="${EXPECTED_V:-${EXPECTED_S:-}}"
          ACTUAL="$(ssh-keygen -y -f ~/.ssh/sg-ci | ssh-keygen -lf - | awk '{print $2}')"
          if [ -n "$EXPECTED" ]; then
            echo "Expected: $EXPECTED"
            echo "Actual:   $ACTUAL"
            [ "$ACTUAL" = "$EXPECTED" ] || { echo "::error::CI private key does not match expected fingerprint"; exit 1; }
          else
            echo "No SG_EXPECTED_FPR provided; skipping fingerprint assertion."
          fi

      - name: Install lftp
        run: |
          sudo apt-get update -y
          sudo apt-get install -y lftp

      - name: Test SFTP connectivity
        env:
          SG_USER: ${{ secrets.SG_USERNAME }}
          SG_HOST: ${{ secrets.SG_HOST }}
        run: |
          set -euo pipefail
          lftp -u "$SG_USER","" sftp://$SG_HOST \
            -e "set sftp:connect-program \"ssh -a -x -i ~/.ssh/sg-ci -p ${SG_PORT:-18765} -o StrictHostKeyChecking=no\"; \
                set net:max-retries 1; set net:timeout 20; set cmd:fail-exit yes; \
                pwd; cls -la; bye"

      - name: Create deploy markers
        run: |
          echo "deployed $(date -u +'%Y-%m-%dT%H:%M:%SZ') $GITHUB_SHA ($TARGET)" > deploy.txt
          echo "internal $(date -u) $GITHUB_SHA $TARGET" > .ci_deploy_marker.txt

      - name: Deploy via SFTP mirror
        env:
          SG_USER: ${{ secrets.SG_USERNAME }}
          SG_HOST: ${{ secrets.SG_HOST }}
        run: |
          set -euo pipefail
          echo "Deploying to $SG_USER@$SG_HOST:${DEST_PATH} (port ${SG_PORT:-18765})"
          lftp -u "$SG_USER","" sftp://$SG_HOST \
            -e "set sftp:connect-program \"ssh -a -x -i ~/.ssh/sg-ci -p ${SG_PORT:-18765} -o StrictHostKeyChecking=no\"; \
                set net:max-retries 2; set net:timeout 30; set ssl:verify-certificate no; set cmd:fail-exit yes; \
                put -O \"${DEST_PATH}\" deploy.txt; \
                put -O \"${DEST_PATH}\" .ci_deploy_marker.txt; \
                mirror -R --delete --verbose=1 --parallel=4 \
                       --exclude-glob .git/ --exclude-glob .github/ --exclude-glob .vscode/ \
                       --exclude-glob node_modules/ --exclude-glob \"*.md\" \
                       ./ \"${DEST_PATH}\"; \
                echo \"Listing ${DEST_PATH}\"; cls -la \"${DEST_PATH}\"; \
                bye"

      - name: Verify live deploy marker (HTTP)
        run: |
          curl -fsS "$BASE_URL/deploy.txt?nocache=$(date +%s)" | head -n1
