- name: Upload & Deploy (STAGING)
  shell: bash
  env:
    SG_HOST: ${{ secrets.SG_HOST }}
    SG_PORT: ${{ secrets.SG_PORT }}
    SG_USER: ${{ secrets.SG_USER }}
  run: |
    set -euo pipefail
    # Upload to HOME (always exists)
    scp -P "$SG_PORT" -i ~/.ssh/sg_ci -o StrictHostKeyChecking=no site.tar.gz "$SG_USER@$SG_HOST:~/"

    # Remote deploy script (note the indented closing BASH)
    ssh -p "$SG_PORT" -i ~/.ssh/sg_ci -o StrictHostKeyChecking=no "$SG_USER@$SG_HOST" bash -s <<'BASH'
    set -euo pipefail
    DOC="$HOME/public_html/staging"
    mkdir -p "$DOC"
    mv -f "$HOME/site.tar.gz" "$DOC/"
    cd "$DOC"

    rm -rf __new
    mkdir __new
    tar -xzf site.tar.gz -C __new

    if command -v rsync >/dev/null 2>&1; then
      rsync -a --delete __new/ ./
    else
      # Fallback if rsync is unavailable
      shopt -s dotglob
      rm -rf *
      cp -a __new/. ./
    fi

    rm -rf __new site.tar.gz
    ls -la | head -n 40
    BASH
