# .github/workflows/deploy-sftp.yml
name: Deploy to SiteGround (SFTP) — Staging & Prod

on:
  push:
    branches: [main, staging]
  workflow_dispatch:
    inputs:
      target:
        description: "Where to deploy"
        required: true
        default: "staging"
        type: choice
        options: [staging, production]

defaults:
  run:
    shell: bash

concurrency:
  group: deploy-${{ github.event.inputs.target || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SG_PORT: ${{ secrets.SG_PORT }}   # 18765

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select environment (staging/prod)
        run: |
          set -euo pipefail
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TARGET="${{ github.event.inputs.target }}"
          else
            case "${{ github.ref }}" in
              refs/heads/main)    TARGET=production ;;
              refs/heads/staging) TARGET=staging ;;
              *) echo "::error::Unsupported branch ${GITHUB_REF}"; exit 1 ;;
            esac
          fi
          if [ "$TARGET" = "production" ]; then
            DEST_PATH='${{ secrets.SG_DEST_PROD }}'
            BASE_URL='https://claycraze.com'
          else
            DEST_PATH='${{ secrets.SG_DEST_STAGING }}'
            BASE_URL='https://stagi_

