name: Deploy to SiteGround (STAGING)

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SG_CI_KEY }}" > ~/.ssh/sg_ci
          sed -i 's/\r$//' ~/.ssh/sg_ci
          chmod 600 ~/.ssh/sg_ci
          ssh-keyscan -p 18765 claycraze.com >> ~/.ssh/known_hosts

      - name: Deploy to STAGING via SCP
        run: |
          tar --exclude='.git' --exclude='.github' --exclude='README.md' \
              -czf site.tar.gz ./
          scp -i ~/.ssh/sg_ci -P 18765 site.tar.gz \
              ${{ secrets.SG_USER }}@claycraze.com:/home/u1966-olev38ziybsd/staging.claycraze.com
          ssh -i ~/.ssh/sg_ci -p 18765 ${{ secrets.SG_USER }}@claycraze.com \
              'cd /home/u1966-olev38ziybsd/staging.claycraze.com && tar -xzf site.tar.gz && rm site.tar.gz'
