name: Deploy to SiteGround (SFTP)

on:
  push:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: deploy-to-siteground
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SG_PORT: ${{ secrets.SG_PORT }}   # set to 18765 in repo secrets
      SG_DEST: ${{ secrets.SG_DEST }}   # optional; defaults to public_html/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key file
        env:
          PRIV: ${{ secrets.SG_PRIVATE_KEY }}
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          printf '%s' "$PRIV" | tr -d '\r' > ~/.ssh/sg-ci
          chmod 600 ~/.ssh/sg-ci

      - name: Show CI key fingerprint
        run: |
          ssh-keygen -y -f ~/.ssh/sg-ci | ssh-keygen -lf -

      - name: Install lftp
        run: |
          sudo apt-get update -y
          sudo apt-get install -y lftp

      - name: Test SFTP connectivity
        env:
          SG_USER: ${{ secrets.SG_USERNAME }}
          SG_HOST: ${{ secrets.SG_HOST }}
        run: |
          set -euo pipefail
          lftp -u "$SG_USER","" sftp://$SG_HOST <<LFTP_CMDS
