name: Deploy to SiteGround (PROD)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          set -euxo pipefail
          mkdir -p ~/.ssh
          echo "${{ secrets.SG_CI_KEY }}" > ~/.ssh/sg_ci
          sed -i 's/\r$//' ~/.ssh/sg_ci
          chmod 600 ~/.ssh/sg_ci
          ssh-keyscan -p 18765 claycraze.com >> ~/.ssh/known_hosts

      - name: Package & Upload (PROD)
        run: |
          set -euxo pipefail
          # create tarball excluding dev/CI files
          tar --exclude-from=.deployignore -czf site.tar.gz ./
          # upload to docroot
          scp -i ~/.ssh/sg_ci -P 18765 site.tar.gz \
            ${{ secrets.SG_USER }}@claycraze.com:/home/u1966-olev38ziybsd/public_html
          # unpack atomically on server
          ssh -i ~/.ssh/sg_ci -p 18765 ${{ secrets.SG_USER }}@claycraze.com '
            set -euxo pipefail
            cd /home/u1966-olev38ziybsd/public_html
            tar -xzf site.tar.gz
            rm -f site.tar.gz
          '
